name = 'pydantic_decoder'
version = '1.0.1'
description = 'Convert json text back into proper Pydantic models.'
url = 'https://github.com/justengel/pydantic_decoder'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
